[package]
name = 'AptosLockProxy'
version = '1.0.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies]
'ZoinAptosContracts' = { local = "../cross_chain_manager", addr_subst = { "poly" = "0x7b4abaf5dc9c20e9dbb13221f91c55ac5a2034d851e103fd6c048944512f2175" } }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
poly = "0x7b4abaf5dc9c20e9dbb13221f91c55ac5a2034d851e103fd6c048944512f2175"
poly_bridge = "0x7b4abaf5dc9c20e9dbb13221f91c55ac5a2034d851e103fd6c048944512f2175"

