[package]
name = 'PolyBridgeCoin'
version = '1.0.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies]
'ZionLockProxy' = { local = "../lock_proxy" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
bridge_coin = "0xf12a4ff673797d20307f081103186c6a725a6c8609a551bdc13ee30862f2ce15"

