[package]
name = 'AptosTools'
version = '1.0.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies]
'ZionAptosContracts' = { local = "../cross_chain_manager" }
'PolyLockProxy' = { local = "../lock_proxy" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
poly_tools = "0xfaaebd6391bf59da8171d35314e33a79592d25ba12cf6ed126660dee2609e8eb"

